#!/usr/bin/env node
/**
 * extract-tokens.js
 * Reads CSS custom properties from a source file (or uses hardcoded v1 values),
 * writes packages/ui/tokens.ts with the full design token map.
 *
 * Usage: node scripts/extract-tokens.js [--input path/to/styles.css]
 *
 * Hardcoded values are the v1 canonical values from CLAUDE.md and REQUIREMENTS.md.
 * Running with --input will override with parsed values if found.
 */

const fs = require('fs');
const path = require('path');

// Canonical v1 token values — source of truth from CLAUDE.md
const CANONICAL_COLORS = {
  'green-deep':  '#0d2b3e',
  'green-water': '#1a4a6b',
  'amber':       '#e8923a',
  'gold':        '#c9a84c',
  'cream':       '#eef6fb',
  'text-dark':   '#0d1f2d',
  'text-mid':    '#4a6070',
};

const CANONICAL_FONTS = {
  serif:       'Lora',
  display:     'Playfair Display',
  handwritten: 'Caveat',
};

function parseCssVars(cssContent) {
  const varRegex = /--([a-zA-Z0-9-]+)\s*:\s*(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\))/g;
  const found = {};
  let match;
  while ((match = varRegex.exec(cssContent)) !== null) {
    found[match[1]] = match[2];
  }
  return found;
}

function generateTokensTs(colors, fonts) {
  return `// packages/ui/tokens.ts
// Generated by scripts/extract-tokens.js — edit the script, not this file directly.
// Re-run: node scripts/extract-tokens.js

export const colors = ${JSON.stringify(colors, null, 2).replace(/"/g, "'")} as const;

export const fonts = {
  serif:       '${fonts.serif}',
  display:     '${fonts.display}',
  handwritten: '${fonts.handwritten}',
} as const;

export const tailwindThemeExtension = {
  colors,
  fontFamily: {
    serif:       ['${fonts.serif}', 'Georgia', 'serif'],
    display:     ['"${fonts.display}"', 'Georgia', 'serif'],
    handwritten: ['${fonts.handwritten}', 'cursive'],
  },
} as const;

export type ColorToken = keyof typeof colors;
export type FontToken = keyof typeof fonts;
`;
}

function main() {
  const args = process.argv.slice(2);
  const inputFlag = args.indexOf('--input');
  const inputPath = inputFlag >= 0 ? args[inputFlag + 1] : null;

  let colors = { ...CANONICAL_COLORS };

  if (inputPath && fs.existsSync(inputPath)) {
    console.log(`Parsing CSS vars from: ${inputPath}`);
    const css = fs.readFileSync(inputPath, 'utf8');
    const parsed = parseCssVars(css);
    // Merge parsed values, keeping canonical as fallback
    const colorKeyMap = {
      'green-deep': ['green-deep', 'color-green-deep'],
      'green-water': ['green-water', 'color-green-water'],
      'amber': ['amber', 'color-amber'],
      'gold': ['gold', 'color-gold'],
      'cream': ['cream', 'color-cream'],
      'text-dark': ['text-dark', 'color-text-dark'],
      'text-mid': ['text-mid', 'color-text-mid'],
    };
    for (const [token, cssVarNames] of Object.entries(colorKeyMap)) {
      for (const varName of cssVarNames) {
        if (parsed[varName]) {
          colors[token] = parsed[varName];
          break;
        }
      }
    }
  } else {
    console.log('No CSS input file — using canonical v1 token values from CLAUDE.md.');
  }

  const outputPath = 'packages/ui/tokens.ts';
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const content = generateTokensTs(colors, CANONICAL_FONTS);
  fs.writeFileSync(outputPath, content, 'utf8');

  console.log(`Wrote: ${outputPath}`);
  console.log('Colors:', Object.keys(colors).join(', '));
  console.log('Fonts: Lora, Playfair Display, Caveat');
}

main();
