// packages/ui/tokens.ts
// Generated by scripts/extract-tokens.js — edit the script, not this file directly.
// Re-run: node scripts/extract-tokens.js

export const colors = {
  'green-deep': '#0d2b3e',
  'green-water': '#1a4a6b',
  'amber': '#e8923a',
  'gold': '#c9a84c',
  'cream': '#eef6fb',
  'text-dark': '#0d1f2d',
  'text-mid': '#4a6070',
  'facebook': '#1877F2',
} as const;

export const fonts = {
  serif:       'Lora',
  display:     'Playfair Display',
  handwritten: 'Caveat',
} as const;

export const tailwindThemeExtension = {
  colors,
  fontFamily: {
    serif:       ['Lora', 'Georgia', 'serif'],
    display:     ['"Playfair Display"', 'Georgia', 'serif'],
    handwritten: ['Caveat', 'cursive'],
  },
};

export type ColorToken = keyof typeof colors;
export type FontToken = keyof typeof fonts;
